# Generated by Django 5.2.1 on 2025-06-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contato', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
