# Generated by Django 5.2.1 on 2025-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
